spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/customers
        username: estefania
        password: estefaniapwd

#psql -h localhost -p 5432 -U estefania customers
#docker run --name pet-postgres -e POSTGRES_USER=estefania -e POSTGRES_PASSWORD=estefaniapwd -e POSTGRES_DB=customers -d -p 5432:5432 postgres
